[config]
source_file = "Connections.csv"
target_file = "result_connections.csv"
source_file_skip_rows = 3
email_validation = true
position_filter_for = ["App", "Application", "Back End", "Desenvolvedor",
"Developer", "Engineer", "Front End", "Full Stack", "Mobile", "Programador",
"Programmer", "Soft", "Software", "Sistemas", "Systems", "Web"]
